services: docker

env:
  global:
  - IMAGE_NAME: devzx/devops-borat
  - secure: ckA/7wRXmrgqYkOgO4Qp87rwilB15y1idBr4wHCiSK09/fSD1oWup/vhGodwRrZ0ut2DiJRTEXdtcU/D/T8xOOf7Ex4hrFGJKrv6jB1JVAUTF6Wzzo/1qwHTbNHpBJ+pF4Go+jWfkWyqXpJrbnaVvwS2NGeWilLTapS8lemRpl9sMGeH1REua2OPOFz+a9IhUTqFKsLWS76PnP40CkOK1KpKUr6oIu+9u14tAV4YeO2vqxK91C/xVxZgETsEiEXOuoQNovoF8V3hdvbf9c+URcqZ6ED1YuZOn8RUYHtLHMsS1E3JauZJXDCo91p8c2OioqZOroUtJIgYc2ZXajaZZJtvVvd5WcAXixbUX+a6+HXlimfcgc5WmMagE1r/d4cJn3TtrHa07G73Yx8erfyJmWXqqETdL7XzF4sDR7cpUT/XIZbnay9KM1MbIci5yqSlhnHfbRm7+mOuq1yfW+Al2AjHpLIBKHpL2IuIfiGmdUexWIlCqmt6+JKWcEQ1n9CJBE+hnafYBaFJ1zAxyqz++x5zEORiO/LtNJsRFlbMkmotUOCcTc9VEzhSEehbuLsgXTxDIRyIkN4bYgmzi14laxZoGznbjAxCHbZbyivU9sq2+ZvCMl+3w7UfYGY9Ltmiiep4rJUJsfrmmUzXmrgvp/FyONn26e9ekmR923QcPqY=
  - secure: sFq+kC6TG5PJvJJsZZSU5N/rvtfImqr3bWF4pVY8fUFsKblQtM0peo6zdZaKyfJCIo2NFw4AlZknb1duygWQ2khFHHu0oZ3hnpn+YyPvWzIX0dHZETna4hsngrevoabJjghyWGUDUEoEQfXmCowSUbIVjeEMi3GTAByZ69YLfZMb9UiCJPAo/DkaESULXQjfxc+kDvd7d1+E13+xcnXPQ9RrKcwzZi49tVnPtVyCxKfTDO6f2AIYnyxLpVIK3ssHaNTOvFrlDdat1WMfnYEKbewuc/jSR4/g+KIeH0oa0th9RV2YGAy99NWzz74utiYqe/0a2Yfc1VLeAO1jnRpMyCrPxJ0Wpz+eOZ5Usg7/oZJntxUEXMhi/3I928Sqb32jc8vN7F1Stl0WEE1VRHOLedRSPTHZHmN3UTjC+nEpqFVSO9El7YckxD4zd3apLHHkE4aYbBTe0lzPmlyoYvHfWO/E7ROcoypBIzkaenMLNUukgyiQNbPpGb0dUmq4wts8wEh7h5XPQCAiJlNNCn9aCCn87mohD8Ii3XyTrfiAJixiFSw4dbhi/7eqqtvSibGs/7iElzu9fr7u5Azk+CNdh4/JeoSbpFn+kDZIJdDNMpFHycQj3Z4NXPfWuuvpeSNQWq2X7ZpDps8DlygtuwYiLedyiqoDLUeAbv+EFfFHtQ0=

install: true

notfications:
  email: false

script:
  - docker build -t $IMAGE_NAME .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker tag $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT

deploy:
  provider: script
  script: docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$TRAVIS_COMMIT
  on:
    branch: master
