services: docker

env:
  global:
    - IMAGE_NAME: devzx/devops-borat
  matrix:
    secure: YIO1hG2JTDD15jUBNzvHKKPP7LyKlZ+jegB755btfwoHSHDTzB8GEeXH9Bc6ciix91WIZ9rZir5Qvd6GN8eHmvci5SFSbe0qp4APMU2bIuHxD42OTwuV7o1+E+dQuO4DUJBZZR2Iw7YxOtQDOR5p2M0qyQo/9tfZn+4MDnOCjcUKttTo2dl91KNPkt48a9xe17dWD/F9x+H+4C1QcSkOzlm6u7JYmDyqWzYAOpVu7Iu13/+jim1jbJKAbpSzkxzsqonDOMR6056cPmaF/a+63fHi8/HLVNg8dLdU9funMamXMJ6uutpT/n0Dxs3xMD1LYraEsuGTCBgfWFAwKLHn7QKvfzsIF3uDb4YvbeNpjyakPlqjDNOeKA0Dv6wco2zPRdcBO3noLVfk3SYi5uGTOht1/1EzQURnETWdSiOdXmJnJO20TayHy+9k48lqpdoCGBbhITeORN6uaMyJBBIo4w9lZSZAxZebIWBdTlzJm9YRWLkizucGGLN/732U8DUXLZlNlw8cuE4uCQdhrU53CtB3HYJGTWCzfjgHJpYejV21z6Lm6zWbQA1kKMCWmesUCgIxRn/CqU2J/Y0JphPdEtygdSvGy6oiVct0sZheEOoENMr18a9kP50vvJ+GRfvbzL0MRnRuT/rCdKawJ73tBTIYlFP0Bk5TKNy1PjFY018=

install: true

notfications:
  email: false

script:
  - docker build -t $IMAGE_NAME .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker tag $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT

deploy:
  provider: script
  script: docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$TRAVIS_COMMIT
  on:
    branch: master
